targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.g.dart']}
      freezed:freezed:
        enabled: true
        options: 
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.freezed.dart']}
      json_serializable:
        options:
          field_rename: snake
          checked: true
